[colors.primary]
background = '#141312'
foreground = '#e5e2e0'

[colors.cursor]
text = '#141312'
cursor = '#e5e2e0'

[colors.vi_mode_cursor]
text = '#141312'
cursor = '#c5c8bc'

[colors.search.matches]
foreground = '#464741'
background = '#c1c8c7'

[colors.search.focused_match]
foreground = '#464741'
background = '#c5c8bc'

[colors.footer_bar]
foreground = '#464741'
background = '#e5e2e0'

[colors.hints.start]
foreground = '#464741'
background = '#c7c7c1'

[colors.hints.end]
foreground = '#464741'
background = '#c7c7c1'

[colors.selection]
text = '#c7c7be'
background = '#464741'


[colors.normal]
black   = '#464741'
red     = '#ffb4ab'
green   = '#c5c8bc'
yellow  = '#c7c7c1'
blue    = '#c1c8c7'
magenta = '#c5c8bc'
cyan    = '#c7c7c1'
white   = '#e5e2e0'


[colors.bright]
black   = '#90918a'
red     = '#ffb4ab'
green   = '#c5c8bc'
yellow  = '#c7c7c1'
blue    = '#c1c8c7'
magenta = '#c5c8bc'
cyan    = '#c7c7c1'
white   = '#e5e2e0'


[colors.dim]
black   = '#464741'
red     = '#ffb4ab'
green   = '#c5c8bc'
yellow  = '#c7c7c1'
blue    = '#c1c8c7'
magenta = '#c5c8bc'
cyan    = '#c7c7c1'
white   = '#e5e2e0'
